_wandb:
    value:
        cli_version: 0.21.4
        e:
            m036h940afj3j2jqn3px6tgz2rs5b5wr:
                cpu_count: 32
                cpu_count_logical: 32
                disk:
                    /:
                        total: "206057766912"
                        used: "195381841920"
                email: anhloi610@gmail.com
                executable: /home/huong.nguyenthi2/miniconda3/envs/kv_env/bin/python
                git:
                    commit: 47aff15439a227a39a6ee7353c071fded8b33e90
                    remote: git@github.com:NRI12/SLR_PROJECT.git
                host: hpc-gw.local
                memory:
                    total: "337493426176"
                os: Linux-4.18.0-348.12.2.el8_5.x86_64-x86_64-with-glibc2.28
                program: -m src.script.train_rgb
                python: CPython 3.12.0
                root: .
                startedAt: "2025-09-13T09:21:56.253223Z"
                writerId: m036h940afj3j2jqn3px6tgz2rs5b5wr
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 9
                - 41
                - 50
                - 103
            "2":
                - 1
                - 9
                - 41
                - 50
                - 103
            "3":
                - 7
                - 13
                - 15
                - 66
            "4": 3.12.0
            "5": 0.21.4
            "12": 0.21.4
            "13": linux-x86_64
annotation_file:
    value: /home/huong.nguyenthi2/SLR_PROJECT/data/annotation/dataset.csv
augmentation_config:
    value: null
batch_size:
    value: 8
data_root:
    value: /home/huong.nguyenthi2/SLR_PROJECT/data/processed
learning_rate:
    value: 0.001
modalities:
    value:
        - rgb
num_classes:
    value: 272
num_test_clips:
    value: 5
num_workers:
    value: 4
output_format:
    value: CTHW
pin_memory:
    value: true
target_fps:
    value: null
target_frames:
    value: 16
video_size:
    value:
        - 112
        - 112
weight_decay:
    value: 0.0001
