
_target_: src.models.hrnet.PoseHighResolutionNet

name: hrnet_w32
num_joints: 133
stem_inplanes: 64
final_conv_kernel: 1

stage2:
  num_modules: 1
  num_branches: 2
  num_blocks: [4, 4]
  num_channels: [32, 64]
  block: BASIC
  fuse_method: SUM

stage3:
  num_modules: 4
  num_branches: 3
  num_blocks: [4, 4, 4]
  num_channels: [32, 64, 128]
  block: BASIC
  fuse_method: SUM
stage4:
  num_modules: 3
  num_branches: 4
  num_blocks: [4, 4, 4, 4]
  num_channels: [32, 64, 128, 256]
  block: BASIC
  fuse_method: SUM