_target_: src.models.hrnet.PoseHighResolutionNet  
name: hrnet_w48

MODEL:
  NUM_JOINTS: 133
  INIT_WEIGHTS: true
  PRETRAINED: ""
  EXTRA:
    FINAL_CONV_KERNEL: 1
    PRETRAINED_LAYERS: ['*']
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      NUM_BLOCKS: [4, 4]
      NUM_CHANNELS: [48, 96]
      BLOCK: BASIC
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      NUM_BLOCKS: [4, 4, 4]
      NUM_CHANNELS: [48, 96, 192]
      BLOCK: BASIC
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      NUM_BLOCKS: [4, 4, 4, 4]
      NUM_CHANNELS: [48, 96, 192, 384]
      BLOCK: BASIC
      FUSE_METHOD: SUM