_wandb:
    value:
        cli_version: 0.21.4
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 9
                - 41
                - 50
                - 103
            "3":
                - 13
                - 15
            "4": 3.12.0
            "5": 0.21.4
            "12": 0.21.4
            "13": linux-x86_64
