defaults:
  - data: dataset

checkpoint:
  dir: /home/huong.nguyenthi2/SLR_PROJECT/src/checkpoint
  url: https://download.pytorch.org/models/raft_large_C_T_SKHT_V2-ff5fadd5.pth
  filename: raft_large_C_T_SKHT_V2-ff5fadd5.pth

gpu_id: 7

optical_flow:
  output_folder: optical_flow

logging:
  level: INFO
  save_path: /home/huong.nguyenthi2/SLR_PROJECT/src/logs